In [1]:
!pip install scgraph==2.1.0         # Python package used to compute paths and distances on a real-world transportation network
!pip install scgraph_data==2.0.0    # Python package used to compute paths and distances on a real-world transportation network

Collecting scgraph==2.1.0
  Obtaining dependency information for scgraph==2.1.0 from https://files.pythonhosted.org/packages/a6/29/79a0d8f5eb119014a4553709c4de93af7d5a0a058b7fbc1739e194b21aa7/scgraph-2.1.0-py3-none-any.whl.metadata
  Downloading scgraph-2.1.0-py3-none-any.whl.metadata (9.4 kB)
Downloading scgraph-2.1.0-py3-none-any.whl (944 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 944.1/944.1 kB 9.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: scgraph
  Attempting uninstall: scgraph
    Found existing installation: scgraph 1.5.0
    Uninstalling scgraph-1.5.0:
      Successfully uninstalled scgraph-1.5.0
Successfully installed scgraph-2.1.0
Collecting scgraph_data==2.0.0
  Obtaining dependency information for scgraph_data==2.0.0 from https://files.pythonhosted.org/packages/50/dc/dcbe9bc753208d9296b7a548df92e4267150cf2754419648ec172118886d/scgraph_data-2.0.0-py3-none-any.whl.metadata
  Downloading scgraph_data-2.0.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: scgraph>=2.0.0 in /Users/mjanjevi/anaconda3/lib/python3.11/site-packages (from scgraph_data==2.0.0) (2.1.0)
Downloading scgraph_data-2.0.0-py3-none-any.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 11.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: scgraph_data
  Attempting uninstall: scgraph_data
    Found existing installation: scgraph_data 1.0.1
    Uninstalling scgraph_data-1.0.1:
      Successfully uninstalled scgraph_data-1.0.1
Successfully installed scgraph_data-2.0.0

In [2]:
# Import all required packages

import pandas as pd                   # For data manipulation and analysis
import gurobipy as grb                # Gurobi optimization library for solving mathematical models
import folium                         # For creating interactive maps
import folium.plugins as plugins      # Additional plugins for folium
from geopy.distance import geodesic   # For calculating geodesic distances between two points


import scgraph                                                  # For computing paths and distances on a real-world transportation network
from scgraph.geographs.us_freeway import us_freeway_geograph    # Data on US highway network (for road paths and distances)
from scgraph.geographs.marnet import marnet_geograph            # Data on maritime routes (for ocean paths and distances)
import matplotlib.pyplot as plt                                 # Plotting library

In [4]:
# Function for computing the shortest path between two points on a real road or ocean network

def shortest_path(origin, destination, mode, result, unit='mi'):

    # Extract coordinates from origin and destination objects
    origin_coordinates = (origin.lat, origin.lon)
    destination_coordinates = (destination.lat, destination.lon)

    # Calculate the shortest path on the ocean network
    if mode == 'ocean':
        output = marnet_geograph.get_shortest_path(
            origin_node={"latitude": origin.lat, "longitude": origin.lon},
            destination_node={"latitude": destination.lat, "longitude": destination.lon},
            output_units= unit
        )

    # Calculate the shortest path on the road network
    elif mode == 'road':
        output = us_freeway_geograph.get_shortest_path(
            origin_node={"latitude": origin.lat, "longitude": origin.lon},
            destination_node={"latitude": destination.lat, "longitude": destination.lon},
            output_units= unit
        )

    # Return the total distance of the path
    if result == 'distance':
        return output['length']

    # Return the coordinates representing the path
    elif result == 'coordinate_path':
        return output['coordinate_path']

In [5]:
# Function for computing the shortest path between two points on a real road or ocean network

def shortest_path(origin, destination, mode, result, unit='mi'):

    # Extract coordinates from origin and destination objects
    origin_coordinates = (origin.lat, origin.lon)
    destination_coordinates = (destination.lat, destination.lon)

    # Calculate the shortest path on the ocean network
    if mode == 'ocean':
        output = marnet_geograph.get_shortest_path(
            origin_node={"latitude": origin.lat, "longitude": origin.lon},
            destination_node={"latitude": destination.lat, "longitude": destination.lon},
            output_units= unit
        )

    # Calculate the shortest path on the road network
    elif mode == 'road':
        output = us_freeway_geograph.get_shortest_path(
            origin_node={"latitude": origin.lat, "longitude": origin.lon},
            destination_node={"latitude": destination.lat, "longitude": destination.lon},
            output_units= unit
        )

    # Return the total distance of the path
    if result == 'distance':
        return output['length']

    # Return the coordinates representing the path
    elif result == 'coordinate_path':
        return output['coordinate_path']

In [6]:
# Class representing a DistributionCenter object

class DistributionCenter():
    def __init__(self, ID, name, lat, lon, demand):
        self.ID = ID              # DistributionCenter's ID
        self.name = name          # DistributionCenter's name
        self.lat = lat            # DistributionCenter's latitude
        self.lon = lon            # DistributionCenter's longitude
        self.demand = demand      # DistributionCenter's demand


# Class representing a Supplier object

class Supplier():
    def __init__(self, ID, name, lat, lon, country, supply, purchase_price):
        self.ID = ID                              # Supplier's ID
        self.name = name                          # Supplier's name
        self.lat = lat                            # Supplier's latitude
        self.lon = lon                            # Supplier's longitude
        self.country = country                    # Supplier's country
        self.supply = supply                      # Supplier's available supply
        self.purchase_price = purchase_price      # Supplier's purchase price


# Class representing a Port object

class Port():
    def __init__(self, ID, name, lat, lon, dwell_time):
        self.ID = ID                  # Port's ID
        self.name = name              # Ports's name
        self.lat = lat                # Ports's latitude
        self.lon = lon                # Ports's longitude
        self.dwell_time = dwell_time  # Ports's dwell time

In [8]:
# File containing supplier data
supplier_data_file = 'https://raw.githubusercontent.com/scm275/problem_sets_scm275/main/test/suppliers.csv'

# Loading supplier data into a pandas DataFrame
suppliers_df = pd.read_csv(supplier_data_file)

# Displaying the first few rows of the DataFrame to verify the data
suppliers_df.head()

   ID          name    country   supply        lat         lon  purchase_price
0  s1      Haiphong    Vietnam  1610000  20.853610  106.577143            10.2
1  s2  Laem Chabang   Thailand  1690000  13.380857  101.024152            11.2
2  s3      Shenzhen      China  1390000  23.105174  113.785356             9.7
3  s4       Colombo  Sri Lanka  1150000   6.886693   79.918738            11.9
4  s5        Callao       Peru  1980000 -12.052263  -77.139113            13.7

In [9]:
# File containing distribution center data
dc_file ='https://raw.githubusercontent.com/scm275/problem_sets_scm275/main/mo_problem_set/distribution_centers.csv'

# Loading DC data into a pandas DataFrame
distribution_centers_df = pd.read_csv(dc_file)

# Displaying the first few rows of the DataFrame to verify the data
distribution_centers_df.head()

   ID         name      lat       lon  population  demand
0  d1     New York  40.6943  -73.9249    18908608  189100
1  d2  Los Angeles  34.1141 -118.4068    11922389  119200
2  d3      Chicago  41.8375  -87.6866     8497759   85000
3  d4        Miami  25.7840  -80.2101     6080145   60800
4  d5      Houston  29.7860  -95.3885     5970127   59700

In [11]:
nodes = dict()

# Creating a dictionary of DC objects
distribution_centers = dict()
for i, row in distribution_centers_df.iterrows():
    distribution_centers[row['ID']] = DistributionCenter(ID=row['ID'],           # Customer's ID
                                    name=row['name'],       # DistributionCenter's name
                                    lat=row['lat'],         # DistributionCenter's latitude
                                    lon=row['lon'],         # DistributionCenter's longitude
                                    demand=row['demand'])   # DistributionCenter's demand

# Merging the DC dictionary into the existing nodes dictionary
nodes = {**nodes, **distribution_centers}

# Creating a dictionary of supplier objects
suppliers = dict()
for i, row in suppliers_df.iterrows():
    suppliers[row['ID']] = Supplier(ID=row['ID'],                             # Supplier's ID
                                    name=row['name'],                         # Supplier's name
                                    lat=row['lat'],                           # Supplier's latitude
                                    lon=row['lon'],                           # Supplier's longitude
                                    country=row['country'],                   # Supplier's country
                                    purchase_price=row['purchase_price'],     # Supplier's purchase price
                                    supply=row['supply'])                     # Supplier's available supply

# Merging the suppliers dictionary into the existing nodes dictionary
nodes = {**nodes, **suppliers}

# Differentiating between US and international suppliers

US_suppliers = {s: supplier for s, supplier in suppliers.items() if supplier.country == 'US'}
INTL_suppliers = {s: supplier for s, supplier in suppliers.items() if supplier.country != 'US'}


#### Visualizing node objects

In [13]:
# Initialize an empty list to hold rows
rows = []

# Loop through US_suppliers and distribution_centers
for s, supplier in US_suppliers.items():
    for d, distribution_center in distribution_centers.items():
        rows.append({"s": s, "d": d, 'test': shortest_path(origin = supplier, destination = distribution_center, mode = 'road', result = 'coordinate_path', unit = 'km')})

# Create a DataFrame from the rows
df = pd.DataFrame(rows)

# Display the DataFrame
df

       s    d                                               test
0     s8   d1  [[37.9722, -122.0016], [38.004, -122.037], [38...
1     s8   d2  [[37.9722, -122.0016], [37.962, -122.051], [37...
2     s8   d3  [[37.9722, -122.0016], [38.004, -122.037], [38...
3     s8   d4  [[37.9722, -122.0016], [37.962, -122.051], [37...
4     s8   d5  [[37.9722, -122.0016], [37.962, -122.051], [37...
..   ...  ...                                                ...
475  s13  d76  [[38.6359, -90.2451], [38.632, -90.242], [38.6...
476  s13  d77  [[38.6359, -90.2451], [38.632, -90.242], [38.6...
477  s13  d78  [[38.6359, -90.2451], [38.632, -90.242], [38.6...
478  s13  d79  [[38.6359, -90.2451], [38.632, -90.242], [38.6...
479  s13  d80  [[38.6359, -90.2451], [38.619, -90.264], [38.6...

[480 rows x 3 columns]

In [14]:
df.to_csv('test.csv')